# Generated by Django 2.2.14 on 2020-08-06 20:55

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('url', models.URLField(help_text='File reference link (eg. http://localhost:8000/image.png)', max_length=1024)),
                ('size', models.IntegerField(help_text='File size in bytes')),
                ('name', models.CharField(help_text='Common File Name (eg. Image.png)', max_length=1024)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(choices=[('FRIENDSHIP', 'Friendship'), ('LEAGUE', 'League'), ('CUP', 'Cup')], help_text='Match type (eg. cup)', max_length=64)),
            ],
            options={
                'db_table': '_match',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the player is active or retired')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_photos', to='models.File')),
            ],
            options={
                'db_table': '_player',
            },
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': '_player_position',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, default='No description available')),
                ('market_value', models.FloatField(default=0, help_text='Market value of the team in USD')),
                ('identity_docs', models.ManyToManyField(help_text='Documents to indentify the team (constitutive act, registration, etc.)', related_name='team_identity_docses', to='models.File')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_logos', to='models.File')),
                ('rival', models.ForeignKey(blank=True, help_text="Team's biggest rival", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rival_teams', to='models.Team')),
            ],
            options={
                'db_table': '_team',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('min', models.IntegerField(default=0, help_text='Minute of the goal')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='models.Match')),
                ('player', models.ForeignKey(help_text='Player that score', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='models.Player')),
            ],
            options={
                'db_table': '_score',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_players', to='models.PlayerPosition'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='models.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_matches', to='models.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_matches', to='models.Team'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('teams', models.ManyToManyField(db_table='_user__teams', help_text='User team preferences', related_name='users', to='models.Team')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': '_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
