---
exclude_paths:
  - "**.md"
  - "requirements.txt"
  - "docs/seed/**"
  - "models/migrations/*"
  - "seed/requirements.txt"
  - "seed/tests/**"
  - "tests/**"
  - ".data/**"
  - ".git/**"
  - ".github/**"
  - ".venv/**"
  - ".vscode/**"

  # - "bin/**"
  # - "seed/app/**"
  # - "seed/models/**"
  # - "seed/mutations/**"
  # - "seed/routes/**"
  # - "seed/schema/**"
  # - "seed/serializers/**"