version: "3.7"

services:

  django:
    build:
      context: ../../.
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8008
    volumes:
      - ../../.:/app
    ports:
      - "8008:8008"
    environment:
      - USE_DOCKER=true
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - ../../.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"