version: "3.7"

services:

  django:
    build:
      context: ../../.
      dockerfile: Dockerfile
    command: /bin/sh -c "python manage.py runserver 0.0.0.0:${DJANGO_PORT}; celery -A app worker -l INFO"
    volumes:
      - ../../.:/app
    environment:
      - USE_DOCKER=true
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    volumes:
      - ../../.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      driver: none
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: "redis:alpine"
    logging:
      driver: none
    ports:
      - "${REDIS_PORT}:6379"