#
# __Seed builder__
#   AUTO_GENERATED (Read only)
#   Modify via builder
#
#   Guidelines:
#      - Use template as base for fixture creation
#      - Run with > python3 manage.py loaddata fixtures/*.yaml
#

## USERS

- model: models.user
  pk: 1
  fields:
    username: "admin@email.com"
    first_name: "Admin"
    last_name: "Django"
    email: "admin@email.com"
    password: "pbkdf2_sha256$150000$jMOqkdOUpor5$kU/QofjBsopM+CdCnU2+pROhtnxd5CZc7NhUiXNTMc0="
    is_active: true
    is_superuser: true
    is_staff: true
    last_login: "2020-01-01T12:00:00+00:00"
    date_joined: "2020-01-01T12:00:00+00:00"
    teams: []

## FILES

- model: models.File
  pk: 1
  fields:
    url: "https://st-listas.20minutos.es/images/2010-01/177732/1966423_640px.jpg?1518458710"
    size: 0
    name: "file"